// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ShRUtuWJbz7lBH2dJ8MuLvsJk13a8S8',
    appId: '1:6774690708:android:98fd7ffe08972e49477581',
    messagingSenderId: '6774690708',
    projectId: 'almalak-ab478',
    databaseURL: 'https://almalak-ab478-default-rtdb.firebaseio.com',
    storageBucket: 'almalak-ab478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgCm5yJyZNmnUoRizascaW38nbiegNfbo',
    appId: '1:6774690708:ios:1348acd5cb6131d9477581',
    messagingSenderId: '6774690708',
    projectId: 'almalak-ab478',
    databaseURL: 'https://almalak-ab478-default-rtdb.firebaseio.com',
    storageBucket: 'almalak-ab478.appspot.com',
    iosClientId: '6774690708-br200cmrd04nhifvbh65ot9c6oc3dckm.apps.googleusercontent.com',
    iosBundleId: 'com.almalak.users',
  );
}
